name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: totally-real-server

    steps:
      - name: Print secrets
        run: |
          echo "DB_DATASOURCE: ${{ secrets.DB_DATASOURCE }}"
          echo "DB_USERNAME: ${{ secrets.DB_USERNAME }}"
          echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
          echo "MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}"
          echo "MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}"
          echo "JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}"
      - name: test secret
        run: printenv
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        env:
          DB_DATASOURCE: ${{ secrets.DB_DATASOURCE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
